FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y gnupg gnupg2 software-properties-common wget zip && \
    apt-get upgrade -y

# Instalar Terraform
RUN wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor |  tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null && \
    gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint && \
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" |  tee /etc/apt/sources.list.d/hashicorp.list && \
    apt-get update && \
    apt-get install -y terraform

# Instalar .NET 8
RUN apt-get install -y dotnet-sdk-8.0 && \
    apt-get install -y aspnetcore-runtime-8.0 && \
    dotnet tool install -g Amazon.Lambda.Tools

# Limpieza
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
