version: 0.2

env:
  secrets-manager:
    AMPCONF: amplifyconfiguration.json

phases:
  build:
    commands:
      - apt-get update
      - apt-get -y install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - cd vision-web
      - echo $AMPCONF > ./src/amplifyconfiguration.json
      - npm ci
      - npx cypress run --component
artifacts:
  files:
    - 'vision-web/cypress/screenshots/**/*'