version: 0.2

phases:
  build:
    commands:
      - sleep 300
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      # - curl -X POST -d {} "$URL" -H "Content-Type: application/json"
      - echo "Deploy app $APP_ID branch $BRANCH_NAME"
      - JOB_ID=$(aws amplify start-job --app-id $APP_ID --branch-name $BRANCH_NAME --commit-id $CODEBUILD_RESOLVED_SOURCE_VERSION --job-type RELEASE | jq -r '.jobSummary.jobId')
      - echo "Release started"
      - echo "Job ID is $JOB_ID"
      - while [[ "$(aws amplify get-job --app-id $APP_ID --branch-name $BRANCH_NAME --job-id $JOB_ID | jq -r '.job.summary.status')" =~ ^(PENDING|RUNNING)$ ]]; do sleep 1; done
      - JOB_STATUS="$(aws amplify get-job --app-id $APP_ID --branch-name $BRANCH_NAME --job-id $JOB_ID | jq -r '.job.summary.status')"
      - echo "Job finished"
      - echo "Job status is $JOB_STATUS"
      - if [[ "$JOB_STATUS" == "FAILED" ]]; then exit 1; fi
