version: 0.2

phases:
  pre_build:
    commands:
      - FOLDER=`echo ${CODEBUILD_INITIATOR##*-}`
      - cd infra/infra_auto/environments/$FOLDER
      # - apt-get update 
      # - apt-get install -y dotnet-sdk-8.0
      # - apt-get install -y aspnetcore-runtime-8.0
      #- dotnet tool install -g Amazon.Lambda.Tools
      - export PATH="$PATH:/root/.dotnet/tools"
      # # - apt-get install -y gnupg gnupg2 software-properties-common wget zip
      # # - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor |  tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
      # # - gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint 
      # # - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" |  tee /etc/apt/sources.list.d/hashicorp.list
      # # - apt update
      # # - apt-get install -y terraform
      # # - /bin/bash ../../../infra_manual/auxiliar_files/bash_scripts/install_dotnet.sh
      # - /bin/bash ../../../infra_manual/auxiliar_files/bash_scripts/install_terraform.sh
  build:
    commands:
      # - FOLDER=`echo ${CODEBUILD_INITIATOR##*-}`
      # - cd infra/infra_auto/environments/$FOLDER
      # - "terraform -chdir=infra/infra_auto/environments/$FOLDER init"
      # - "terraform -chdir=infra/infra_auto/environments/$FOLDER apply --auto-approve"
      - terraform init
      - export TF_VAR_api_deployed_at=$(date +%s)
      - ls -lR .terraform
      - terraform apply --auto-approve
      - ls -la .terraform
cache:
 paths:
   - 'infra/infra_auto/environments/$FOLDER/.terraform/**/*'