version: 0.2

phases:
  build:
    commands:
      - sudo apt-get update && sudo apt-get install -y dotnet-sdk-8.0
      - sudo apt-get install -y aspnetcore-runtime-8.0
      - dotnet tool install -g Amazon.Lambda.Tools
artifacts:
  files:
    - '**/*'